### ISSUE TITLE
Does it prefer madlib0 over mpg123?

### ISSUE THREAD

**Issue by hobbieman** [alsaplayer/alsaplayer#24]
If both are installed, how do I know if alsaplayer is using libmad0 vs mpg123 for decoding MP3's?

**Comment by domichel** [comment]
Le Mon, 02 Sep 2019 15:06:48 -0700,
hobbieman <notifications@github.com> a écrit :

> If both are installed, how do I know if alsaplayer is using libmad0
> vs mpg123 for decoding MP3's?
> 

libmad will be used.

The configure output will show
  Use libmad shared library:          yes

Thanks for pointing that out. I should update the README because mpg123
support was removed.

-- 
If you have a problem and you are not doing anything to fix it, you are
at the heart of the problem.
